<?php

return [
    'actions' => [
        'view' => 'View',
        'create' => 'Create',
        'edit' => 'Edit',
        'delete' => 'Delete',
        'approve' => 'Approve',
        'export' => 'Export',
    ],

    'modules' => [
        'users' => 'User Management',
        'roles' => 'Roles & Permissions',
        'students' => 'Student Records',
        'faculty' => 'Faculty & Staff',
        'departments' => 'Departments',
        'programs' => 'Programs',
        'courses' => 'Courses',
        'enrollments' => 'Enrollments',
        'applications' => 'Admissions Applications',
        'fees' => 'Fees & Payments',
        'attendance' => 'Attendance',
        'grades' => 'Grades',
        'lms' => 'Learning Materials',
        'exams' => 'Exams & Quizzes',
        'reports' => 'Reports',
        'settings' => 'System Settings',
        'evoting' => 'E-Voting & Student Leadership',
        'library' => 'Library Services',
        'human_resources' => 'Human Resources',
        'facilities' => 'Estates & Facilities',
        'library_catalogue' => 'Library Catalogue',
        'library_circulation' => 'Library Circulation',
        'hr_core' => 'HR Core & Administration',
        'hr_attendance' => 'HR Time & Attendance',
        'hr_payroll' => 'HR Payroll & Benefits',
        'hr_recruiting' => 'HR Talent Sourcing',
        'hr_talent' => 'HR Talent Management',
        'facilities_rooms' => 'Facilities Rooms & Assets',
        'facilities_requests' => 'Facilities Bookings & Maintenance',
        'finance_hub' => 'Finance & Bursar Hub',
        'revenue' => 'Revenue & Income',
        'budgets' => 'Department Budgets',
        'expenses' => 'Expenditures',
        'payables' => 'Accounts Payable',
        'receivables' => 'Accounts Receivable',
        'payroll' => 'Payroll Management',
        'assets' => 'Asset Management',
        'banking' => 'Banking & Cash',
        'financial_statements' => 'Financial Statements',
    ],

    'defaults' => [
        'super_administrator' => [
            'name' => 'Super Administrator',
            'guard_role' => 'admin',
            'description' => 'Full system access for institutional administrators.',
        ],
        'registrar' => [
            'name' => 'Registrar',
            'guard_role' => 'admin',
            'description' => 'Manages student records, enrollments, programs, and academic reporting.',
        ],
        'dean' => [
            'name' => 'Dean',
            'guard_role' => 'faculty',
            'description' => 'Oversees faculty, departments, programs, and academic performance.',
        ],
        'head_of_department' => [
            'name' => 'Head of Department',
            'guard_role' => 'faculty',
            'description' => 'Manages department courses, lecturers, attendance, and grades.',
        ],
        'lecturer' => [
            'name' => 'Lecturer',
            'guard_role' => 'faculty',
            'description' => 'Manages assigned courses, materials, attendance, assignments, exams, and grades.',
        ],
        'finance_officer' => [
            'name' => 'Finance Officer',
            'guard_role' => 'admin',
            'description' => 'Manages fee structures, payments, receipts, and financial reports.',
        ],
        'admissions_officer' => [
            'name' => 'Admissions Officer',
            'guard_role' => 'admin',
            'description' => 'Reviews applications and admission payment verification.',
        ],
        'student' => [
            'name' => 'Student',
            'guard_role' => 'student',
            'description' => 'Access to personal courses, fees, attendance, grades, LMS, and exams.',
        ],
        'parent_guardian' => [
            'name' => 'Parent / Guardian',
            'guard_role' => 'parent',
            'description' => 'Read-only guardian access to student progress and finance information.',
        ],
        'librarian' => [
            'name' => 'Librarian',
            'guard_role' => 'admin',
            'description' => 'Oversees library catalogues, loans, reservations, and fines.',
        ],
        'assistant_librarian' => [
            'name' => 'Assistant Librarian',
            'guard_role' => 'admin',
            'description' => 'Supports circulation, cataloguing, and shelf operations.',
        ],
        'hr_manager' => [
            'name' => 'HR Manager',
            'guard_role' => 'admin',
            'description' => 'Manages staff records, leave requests, and employee engagement.',
        ],
        'hr_specialist' => [
            'name' => 'HR Specialist',
            'guard_role' => 'admin',
            'description' => 'Supports staff administration and employee lifecycle workflows.',
        ],
        'estates_manager' => [
            'name' => 'Estates Manager',
            'guard_role' => 'admin',
            'description' => 'Coordinates facilities maintenance, room bookings, and estate planning.',
        ],
        'facilities_officer' => [
            'name' => 'Facilities Officer',
            'guard_role' => 'admin',
            'description' => 'Handles rooms, maintenance, and facilities service requests.',
        ],
    ],
];
